/**
 * Update transaction for accepting requests and modifying the MPF.
 *
 * This module provides the transaction builder for the Modify operation,
 * which allows the token owner to accept pending requests and update
 * the MPF root. The update transaction:
 * - Spends the State UTxO with the Modify redeemer
 * - Spends one or more Request UTxOs with the Contribute redeemer
 * - Produces a new State UTxO with updated MPF root
 * - Includes proofs for each request being processed
 * @module
 */

import {
    Data,
    mConStr0,
    mConStr1,
    mConStr2,
    mOutputReference
} from '@meshsdk/core';

import { Context } from './context';
import { Proof } from '../mpf/lib';
import { serializeProof } from '../trie/proof';
import { nullHash, OutputRef, outputRefEqual, toHex } from '../lib';
import { unmkOutputRefId } from '../outputRef';
import {
    signAndSubmit,
    WithTxHash,
    WithUnsignedTransaction
} from './context/lib';
import { Log } from '../log';

/** Estimated execution cost for the Modify redeemer (State spending) */
const guessingLowCost = {
    mem: 1_000_000,
    steps: 1_000_000_000
};

/** Estimated execution cost for the Contribute redeemer (Request spending) */
const guessingRequestCost = {
    mem: 200_000,
    steps: 100_000_000
};

/**
 * Create and submit an update transaction.
 *
 * Signs and submits a transaction that processes pending requests.
 *
 * @param context - The transaction context
 * @param tokenId - The asset name of the token to update
 * @param requireds - Optional list of specific requests to process (default: all)
 * @returns Promise resolving to tx hash and new MPF root
 */
export async function update(
    context: Context,
    tokenId: string,
    requireds: OutputRef[] = []
): Promise<WithTxHash<string | null>> {
    return await signAndSubmit(context, async walletAddress => {
        return await updateTransaction(
            context,
            walletAddress,
            tokenId,
            requireds
        );
    });
}

/**
 * Build an unsigned update transaction.
 *
 * Creates a transaction that:
 * 1. Spends the State UTxO with Modify redeemer containing proofs
 * 2. Spends each selected Request UTxO with Contribute redeemer
 * 3. Produces a new State UTxO with updated owner and root
 * 4. Generates MPF proofs by temporarily applying each request
 *
 * The proofs are generated by:
 * - Pausing the indexer to prevent state changes
 * - Temporarily applying each request to the local trie copy
 * - Extracting the proof for each operation
 * - Rolling back the trie after transaction is built
 *
 * @param context - The transaction context
 * @param walletAddress - The wallet address (must be the owner)
 * @param tokenId - The asset name of the token to update
 * @param requireds - Specific requests to include (filtered from available)
 * @returns Promise resolving to unsigned tx and new MPF root
 * @throws Error if token not found or no requests available
 */
export async function updateTransaction(
    context: Context,
    walletAddress: string,
    tokenId: string,
    requireds: OutputRef[],
    txLog?: Log
): Promise<WithUnsignedTransaction<string | null>> {
    const { utxos, collateral, signerHash } =
        await context.addressWallet(walletAddress);

    const { address: cageAddress, cbor: cageCbor } = context.cagingScript;

    const dbState = await context.fetchToken(tokenId);
    if (!dbState) {
        throw new Error(`Token with ID ${tokenId} not found`);
    }
    const { outputRef } = dbState;

    const stateOutputRef = mConStr1([
        mOutputReference(outputRef.txHash, outputRef.outputIndex)
    ]);
    const presents = await context.fetchRequests(tokenId);
    const resolvedPresents = presents.map(present => ({
        ...present,
        resolvedRef: unmkOutputRefId(present.outputRefId)
    }));
    const promoteds = resolvedPresents.filter(present =>
        requireds.some(required =>
            outputRefEqual(present.resolvedRef, required)
        )
    );

    txLog?.debug('tx_build_start', {
        token_id: tokenId,
        requireds_count: requireds.length,
        promoteds_count: promoteds.length,
        state_input: {
            txHash: outputRef.txHash,
            outputIndex: outputRef.outputIndex
        },
        request_inputs: promoteds.map(p => ({
            txHash: p.resolvedRef.txHash,
            outputIndex: p.resolvedRef.outputIndex
        })),
        plutus_state_cost: guessingLowCost,
        plutus_request_cost: guessingRequestCost
    });

    let proofs: Proof[] = [];
    let newRoot: string | null = null;
    const tx = context.newTxBuilder();
    const releaseIndexer = await context.pauseIndexer();
    const { policyId } = context.cagingScript;
    const unit = policyId + tokenId;
    async function onTrie(trie) {
        try {
            for (const promoted of promoteds) {
                proofs.push(await trie.temporaryUpdate(promoted.change));
                tx.spendingPlutusScriptV3()
                    .txIn(
                        promoted.resolvedRef.txHash,
                        promoted.resolvedRef.outputIndex
                    )
                    .txInInlineDatumPresent()
                    .txInRedeemerValue(
                        stateOutputRef,
                        'Mesh',
                        guessingRequestCost
                    )
                    .txInScript(cageCbor);
            }
            if (proofs.length === 0) {
                throw new Error('No requests found');
            }
            const root = trie.root();
            newRoot = root ? toHex(root) : nullHash;
            const newStateDatum = mConStr1([mConStr0([signerHash, newRoot])]);
            const jsonProofs: Data[] = proofs.map(serializeProof);
            tx.selectUtxosFrom(utxos) // select the remaining UTXOs
                .spendingPlutusScriptV3()
                .txIn(outputRef.txHash, outputRef.outputIndex)
                .txInInlineDatumPresent()
                .txInRedeemerValue(
                    mConStr2([jsonProofs]),
                    'Mesh',
                    guessingLowCost
                )
                .txInScript(cageCbor)
                .txOut(cageAddress, [{ unit, quantity: '1' }])
                .txOutInlineDatumValue(newStateDatum, 'Mesh');
            tx.requiredSignerHash(signerHash)
                .changeAddress(walletAddress)
                .txInCollateral(
                    collateral.input.txHash,
                    collateral.input.outputIndex
                );

            await tx.complete();
        } catch (error) {
            trie.rollback();
            releaseIndexer();
            throw new Error(
                `Failed to create or submit a transaction: ${error}`
            );
        }
        await trie.rollback(); // Rollback the trie to the previous state
    }
    await context.trie(tokenId, onTrie);
    releaseIndexer();
    return {
        unsignedTransaction: tx.txHex,
        value: newRoot
    };
}
