name: Continuous Integration of mpfs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  MPFS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up aiken environment
        uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.15

      - name: Test on-chain code
        run: |
          cd on_chain
          aiken check

      - name: Build on-chain code
        run: |
          cd on_chain
          aiken build

      - name: Set up yaci-cli
        run: |
          curl -L https://github.com/bloxbean/yaci-devkit/releases/download/v0.10.6/yaci-cli-0.10.6-linux-X64.zip -o yaci-cli.zip
          unzip yaci-cli.zip
          cd yaci-cli-0.10.6
          ./yaci-cli up --enable-yaci-store &

      - name: Set up javascript environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up off-chain code
        run: |
          cd off_chain
          npm install

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run tests
        run: just test-all
