name: "Publish Docs"

on:
  push:
    branches:
      - main

jobs:
  publishing:
    name: Publish Site
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install mkdocs and dependencies
      run: |
        pip install mkdocs-material
        pip install pymdown-extensions

    - name: Build documentation
      run: |
        mkdocs build --strict
        mkdir -p /tmp/public
        mv site/* /tmp/public

    - name: Publish Documentation
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: /tmp/public
        force_orphan: true
